# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
references:
  workspace_root: &workspace_root
    /tmp/workspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root
jobs:
    maven_build_and_SL_scan:
        docker:
            - image: circleci/openjdk:8-jdk-node
        working_directory: ~/repo
        environment:
            MAVEN_OPTS: -Xmx3200m
            
        steps:
            - *attach_workspace
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "pom.xml" }}
                    # fallback to using the latest cache if no exact match is found
                    - v1-dependencies-
            
            - run: mvn dependency:go-offline
            - save_cache:
                paths:
                    - ~/.m2
                key: v1-dependencies-{{ checksum "pom.xml" }}
                
            # build the apps!!
            - run:
                name: Build the application
                command: |
                    mvn clean package
                    curl https://www.shiftleft.io/download/sl-latest-linux-x64.tar.gz > /tmp/sl.tar.gz && sudo tar -C /usr/local/bin -xzf /tmp/sl.tar.gz
                    sl analyze --wait --tag branch=$CIRCLE_BRANCH --policy 639070ed-7aad-4e53-bd5c-b97190308dc2/first_policy:latest --app tarpit-java-circle /home/circleci/repo/target/tarpit-java.war

    sl_build_rules:
        docker:
            - image: circleci/openjdk:8-jdk-node
        working_directory: ~/repo   
        steps:
            - *attach_workspace
            - run:
                name: Check SAST Analysis
                command: |
                    curl https://www.shiftleft.io/download/sl-latest-linux-x64.tar.gz > /tmp/sl.tar.gz && sudo tar -C /usr/local/bin -xzf /tmp/sl.tar.gz
                    PR_USER=$(echo $CIRCLE_PULL_REQUEST | cut -d '/' -f4)
                    PR_REPO=$(echo $CIRCLE_PULL_REQUEST | cut -d '/' -f5) 
                    PR_NUMBER=$(echo $CIRCLE_PULL_REQUEST | cut -d '/' -f7) 
                    sl check-analysis --app tarpit-java-circle --report  --target=tag.branch=$CIRCLE_BRANCH --github-pr-user=$PR_USER --github-pr-repo=$PR_REPO --github-pr-number=$PR_NUMBER --github-token=$GH_AUTH_TOKEN


workflows:
  version: 2
  build-test:
    jobs:
      - maven_build_and_SL_scan:
          filters:
            branches:
              ignore:
                - develop
                - /feature-.*/
      - sl_build_rules:
          requires:
            - build
          filters:
            branches:
              ignore: 
                - main
